name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Log into docker registry
      run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Tinamous.MeasurementsProcessor.ConsoleHost/Dockerfile --tag docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:${{ github['sha'] }}
    - name: Push Docker image
      run: docker push docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:${{ github['sha'] }}
    - name: Docker tagt latest
      run: docker tag docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:${{ github['sha'] }} docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:latest
    - name: Push Docker latest image
      run: docker push docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:latest

