name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Log into docker registry
      run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Tinamous.MeasurementsProcessor.ConsoleHost/Dockerfile --tag tinamous-measurements-processor:$(date +%s)
    - name: Push Docker image
      run: docker push docker.pkg.github.com/tinamous/tinamous.measurementsprocessor/tinamous-measurements-processor:$(date +%s)

