name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Restore from Tinamous public NuGet repository
      run: dotnet restore -s https://www.myget.org/F/tinamous/api/v3/index.json -s https://api.nuget.org/v3/index.json
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run tests with dotnet
      run: dotnet test --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release -o ./app
